services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - GERADOR_ID_URL=http://gerador-id:3002
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gerador-id:
    build: ../gerador-id
    ports:
      - "3002:3002"

volumes:
  mongo-data:
